language: ruby
rvm:
- 2.2.4
script: "./_script/cibuild.sh && ./_script/test.sh"
deploy:
  skip_cleanup: true
  provider: script
  script: _script/cideploy.sh
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
