# Site settings
title: Poppy Project

default_title:
  en: "Poppy Project: collaborative ecosystem for robotics"
  fr: "Poppy Project : écosystème collaboratif pour la robotique"

description:
  en: "Poppy Project description."
  fr: "Description du Projet Poppy."

# Build settings
# analytics: true
markdown: kramdown
highlighter: rouge

timezone: Europe/Paris

include: [ "_pages" ]

exclude: [
  "bower_components",
  "vendor",
  "README.md",
  "LICENSE.md",
  "CONTRIBUTING.md",
  "Gemfile",
  "Gemfile.lock"
]

permalink: /:categories/:title
default_lang: en

languages:
  - name: English
    key: en
  - name: Français
    key: fr

# Will be overridden by github
github:
  repository_url: https://github.com/poppy-project/poppy-project.org

# HTML compression
compress_html:
  endings: []
  startings: []
