gems:
  - jekyll-sitemap

# Site settings
title: Poppy Project
url: http://sandbox.dcsl.li

description:
  en: >-
    Poppy Project website.
    You will love it.
  fr: >-
    Site du Projet Poppy.

outlinks:
  en:
    - url: https://forum.poppy-project.org
      title: Forum
    - url: https://poppy-project.gitbooks.io/poppy-docs/content/en/
      title: Documentation
  fr:
    - url: https://forum.poppy-project.org
      title: Forum
    - url: https://poppy-project.gitbooks.io/poppy-docs/content/fr/
      title: Documentation


# Build settings
markdown: kramdown
highlighter: rouge

# sass:
#   style: compressed

include: [ "_pages" ]

permalink: /:categories/:title
default_lang: en
languages:
  - name: English
    key: en
  - name: Français
    key: fr
