gems:
  - jekyll-sitemap

# Site settings
title: Poppy Project
github:
  url: http://localhost:4000

description:
  en: >-
    Poppy Project website.
    You will love it.
  fr: >-
    Site du Projet Poppy.
email: poppy-project@inria.fr

# Build settings
markdown: kramdown
sass:
  style: compressed
include: [ "_pages" ]
permalink: /:categories/:title
default_lang: en
languages:
  - name: English
    key: en
  - name: Français
    key: fr
