# Site settings
title: Poppy Project
# url: http://poppy-project.github.io/poppy-project.org

description:
  en: >-
    Poppy Project website.
    You will love it.
  fr: >-
    Site du Projet Poppy.

outlinks:
  en:
    - url: https://forum.poppy-project.org
      title: Forum
    - url: http://docs.poppy-project.org/en/
      title: Documentation
  fr:
    - url: https://forum.poppy-project.org
      title: Forums
    - url: http://docs.poppy-project.org/fr/
      title: Documentation


# Build settings
markdown: kramdown
highlighter: rouge

# sass:
#   style: compressed

include: [ "_pages" ]

exclude: [
  "vendor",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]

permalink: /:categories/:title
default_lang: en
languages:
  - name: English
    key: en
  - name: Français
    key: fr
